// Atlas Business System — 50-state seed data.
//
// IMPORTANT: Filing fees and document URLs below are best-effort starting points.
// State fee schedules change. Each entry carries `verified: false` until it has
// been checked against the state's official Secretary of State fee schedule.
// Use the admin UI (/admin/states) to review and correct, then flip `verified`.

export type StateSeed = {
  code: string;
  name: string;
  sos: string;
  search: string;
  notes?: string;
  fees: {
    LLC: { cents: number; time: string; docUrl?: string };
    FOR_PROFIT: { cents: number; time: string; docUrl?: string };
    NON_PROFIT: { cents: number; time: string; docUrl?: string };
  };
};

export const STATES: StateSeed[] = [
  { code: "AL", name: "Alabama", sos: "https://www.sos.alabama.gov/", search: "https://arc-sos.state.al.us/cgi/corpnamebr.pl", fees: { LLC: { cents: 20000, time: "~1-2 weeks" }, FOR_PROFIT: { cents: 20000, time: "~1-2 weeks" }, NON_PROFIT: { cents: 7500, time: "~1-2 weeks" } } },
  { code: "AK", name: "Alaska", sos: "https://www.commerce.alaska.gov/web/", search: "https://www.commerce.alaska.gov/cbp/main/search/entities", fees: { LLC: { cents: 25000, time: "~7-10 business days" }, FOR_PROFIT: { cents: 25000, time: "~7-10 business days" }, NON_PROFIT: { cents: 25000, time: "~7-10 business days" } } },
  { code: "AZ", name: "Arizona", sos: "https://ecorp.azcc.gov/", search: "https://ecorp.azcc.gov/BusinessSearch/BusinessSearch", fees: { LLC: { cents: 5000, time: "~5-10 business days" }, FOR_PROFIT: { cents: 6000, time: "~5-10 business days" }, NON_PROFIT: { cents: 2500, time: "~5-10 business days" } } },
  { code: "AR", name: "Arkansas", sos: "https://www.sos.arkansas.gov/", search: "https://www.ark.org/sos/corps/", fees: { LLC: { cents: 4500, time: "~5-7 business days" }, FOR_PROFIT: { cents: 4500, time: "~5-7 business days" }, NON_PROFIT: { cents: 4500, time: "~5-7 business days" } } },
  { code: "CA", name: "California", sos: "https://www.sos.ca.gov/", search: "https://bizfileonline.sos.ca.gov/search/business", notes: "LLC also subject to $800/yr California franchise tax.", fees: { LLC: { cents: 7000, time: "~5-10 business days (expedited available)" }, FOR_PROFIT: { cents: 10000, time: "~5-10 business days (expedited available)" }, NON_PROFIT: { cents: 3000, time: "~5-10 business days" } } },
  { code: "CO", name: "Colorado", sos: "https://www.sos.state.co.us/", search: "https://www.sos.state.co.us/biz/BusinessSearchCriteria.do", fees: { LLC: { cents: 5000, time: "~24 hours (online)" }, FOR_PROFIT: { cents: 5000, time: "~24 hours (online)" }, NON_PROFIT: { cents: 5000, time: "~24 hours (online)" } } },
  { code: "CT", name: "Connecticut", sos: "https://portal.ct.gov/SOTS", search: "https://service.ct.gov/business/s/onlinebusinesssearch", fees: { LLC: { cents: 12000, time: "~2-3 weeks" }, FOR_PROFIT: { cents: 25000, time: "~2-3 weeks" }, NON_PROFIT: { cents: 5000, time: "~2-3 weeks" } } },
  { code: "DE", name: "Delaware", sos: "https://corp.delaware.gov/", search: "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx", notes: "Delaware is a popular incorporation state; franchises often also need a home-state foreign registration.", fees: { LLC: { cents: 9000, time: "~1-2 business days" }, FOR_PROFIT: { cents: 8900, time: "~1-2 business days" }, NON_PROFIT: { cents: 8900, time: "~1-2 business days" } } },
  { code: "FL", name: "Florida", sos: "https://dos.fl.gov/", search: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName", fees: { LLC: { cents: 12500, time: "~5-7 business days" }, FOR_PROFIT: { cents: 3500, time: "~5-7 business days" }, NON_PROFIT: { cents: 3500, time: "~5-7 business days" } } },
  { code: "GA", name: "Georgia", sos: "https://sos.ga.gov/", search: "https://ecorp.sos.ga.gov/BusinessSearch", fees: { LLC: { cents: 10000, time: "~7-10 business days" }, FOR_PROFIT: { cents: 10000, time: "~7-10 business days" }, NON_PROFIT: { cents: 10000, time: "~7-10 business days" } } },
  { code: "HI", name: "Hawaii", sos: "https://cca.hawaii.gov/businessreg/", search: "https://hbe.ehawaii.gov/documents/search.html", fees: { LLC: { cents: 5000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 5000, time: "~5-7 business days" }, NON_PROFIT: { cents: 5000, time: "~5-7 business days" } } },
  { code: "ID", name: "Idaho", sos: "https://sos.idaho.gov/", search: "https://sosbiz.idaho.gov/search/business", fees: { LLC: { cents: 10000, time: "~1-3 business days" }, FOR_PROFIT: { cents: 10000, time: "~1-3 business days" }, NON_PROFIT: { cents: 10000, time: "~1-3 business days" } } },
  { code: "IL", name: "Illinois", sos: "https://www.ilsos.gov/", search: "https://apps.ilsos.gov/corporatellc/", fees: { LLC: { cents: 15000, time: "~15 business days" }, FOR_PROFIT: { cents: 17500, time: "~15 business days" }, NON_PROFIT: { cents: 17500, time: "~15 business days" } } },
  { code: "IN", name: "Indiana", sos: "https://www.in.gov/sos/", search: "https://bsd.sos.in.gov/publicbusinesssearch", fees: { LLC: { cents: 10000, time: "~1-2 business days (online)" }, FOR_PROFIT: { cents: 9500, time: "~1-2 business days (online)" }, NON_PROFIT: { cents: 9500, time: "~1-2 business days (online)" } } },
  { code: "IA", name: "Iowa", sos: "https://sos.iowa.gov/", search: "https://sos.iowa.gov/search/business/search.aspx", fees: { LLC: { cents: 5000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 5000, time: "~3-5 business days" }, NON_PROFIT: { cents: 5000, time: "~3-5 business days" } } },
  { code: "KS", name: "Kansas", sos: "https://sos.ks.gov/", search: "https://www.kansas.gov/businesscenter/business-search/", fees: { LLC: { cents: 16500, time: "~2-5 business days" }, FOR_PROFIT: { cents: 16500, time: "~2-5 business days" }, NON_PROFIT: { cents: 16500, time: "~2-5 business days" } } },
  { code: "KY", name: "Kentucky", sos: "https://www.sos.ky.gov/", search: "https://web.sos.ky.gov/ftsearch/", fees: { LLC: { cents: 4000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 4000, time: "~5-7 business days" }, NON_PROFIT: { cents: 4000, time: "~5-7 business days" } } },
  { code: "LA", name: "Louisiana", sos: "https://www.sos.la.gov/", search: "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx", fees: { LLC: { cents: 10000, time: "~2-5 business days" }, FOR_PROFIT: { cents: 7500, time: "~2-5 business days" }, NON_PROFIT: { cents: 7500, time: "~2-5 business days" } } },
  { code: "ME", name: "Maine", sos: "https://www.maine.gov/sos/", search: "https://icrs.informe.org/nei-sos-icrs/ICRS?MainFrame=x", fees: { LLC: { cents: 17500, time: "~5-7 business days" }, FOR_PROFIT: { cents: 14500, time: "~5-7 business days" }, NON_PROFIT: { cents: 14500, time: "~5-7 business days" } } },
  { code: "MD", name: "Maryland", sos: "https://sos.maryland.gov/", search: "https://egov.maryland.gov/businessexpress/entitysearch", fees: { LLC: { cents: 10000, time: "~7-10 business days" }, FOR_PROFIT: { cents: 12000, time: "~7-10 business days" }, NON_PROFIT: { cents: 12000, time: "~7-10 business days" } } },
  { code: "MA", name: "Massachusetts", sos: "https://www.sec.state.ma.us/", search: "https://corp.sec.state.ma.us/CorpWeb/CorpSearch/Search.aspx", fees: { LLC: { cents: 50000, time: "~5-10 business days" }, FOR_PROFIT: { cents: 27000, time: "~5-10 business days" }, NON_PROFIT: { cents: 27000, time: "~5-10 business days" } } },
  { code: "MI", name: "Michigan", sos: "https://www.michigan.gov/lara", search: "https://cofs.lara.state.mi.us/SearchApi/Search/Search", fees: { LLC: { cents: 5000, time: "~3-7 business days" }, FOR_PROFIT: { cents: 6000, time: "~3-7 business days" }, NON_PROFIT: { cents: 6000, time: "~3-7 business days" } } },
  { code: "MN", name: "Minnesota", sos: "https://www.sos.state.mn.us/", search: "https://mblsportal.sos.state.mn.us/Business/Search", fees: { LLC: { cents: 15500, time: "~2-4 business days" }, FOR_PROFIT: { cents: 13500, time: "~2-4 business days" }, NON_PROFIT: { cents: 13500, time: "~2-4 business days" } } },
  { code: "MS", name: "Mississippi", sos: "https://www.sos.ms.gov/", search: "https://business.sos.ms.gov/corp/soskb/Corp.asp?PAGE=Search", fees: { LLC: { cents: 5000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 5000, time: "~3-5 business days" }, NON_PROFIT: { cents: 5000, time: "~3-5 business days" } } },
  { code: "MO", name: "Missouri", sos: "https://www.sos.mo.gov/", search: "https://bsd.sos.mo.gov/searchresults.aspx", fees: { LLC: { cents: 5000, time: "~1-3 business days (online)" }, FOR_PROFIT: { cents: 5800, time: "~1-3 business days (online)" }, NON_PROFIT: { cents: 5800, time: "~1-3 business days (online)" } } },
  { code: "MT", name: "Montana", sos: "https://sosmt.gov/", search: "https://businessdatasearch.mt.gov/BusinessSearch/", fees: { LLC: { cents: 3500, time: "~1-3 business days" }, FOR_PROFIT: { cents: 7000, time: "~1-3 business days" }, NON_PROFIT: { cents: 7000, time: "~1-3 business days" } } },
  { code: "NE", name: "Nebraska", sos: "https://sos.nebraska.gov/", search: "https://www.nebraska.gov/sos/corp/corpsearch.cgi", fees: { LLC: { cents: 11000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 6000, time: "~3-5 business days" }, NON_PROFIT: { cents: 6000, time: "~3-5 business days" } } },
  { code: "NV", name: "Nevada", sos: "https://www.nvsos.gov/", search: "https://esos.nv.gov/EntitySearch/OnlineEntitySearch.aspx", notes: "Nevada LLCs also owe a state business license fee.", fees: { LLC: { cents: 42500, time: "~1-2 business days (expedited available)" }, FOR_PROFIT: { cents: 17500, time: "~1-2 business days (expedited available)" }, NON_PROFIT: { cents: 17500, time: "~1-2 business days" } } },
  { code: "NH", name: "New Hampshire", sos: "https://sos.nh.gov/", search: "https://quickstart.sos.nh.gov/online/BusinessInquire", fees: { LLC: { cents: 10000, time: "~2-4 business days" }, FOR_PROFIT: { cents: 10000, time: "~2-4 business days" }, NON_PROFIT: { cents: 10000, time: "~2-4 business days" } } },
  { code: "NJ", name: "New Jersey", sos: "https://www.nj.gov/state/", search: "https://www.njportal.com/DOR/businessnameSearch", fees: { LLC: { cents: 12500, time: "~2-3 weeks" }, FOR_PROFIT: { cents: 12500, time: "~2-3 weeks" }, NON_PROFIT: { cents: 12500, time: "~2-3 weeks" } } },
  { code: "NM", name: "New Mexico", sos: "https://www.sos.state.nm.us/", search: "https://portal.sos.state.nm.us/BFS/online/CorporationSearch", fees: { LLC: { cents: 5000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 10000, time: "~3-5 business days" }, NON_PROFIT: { cents: 10000, time: "~3-5 business days" } } },
  { code: "NY", name: "New York", sos: "https://www.dos.ny.gov/", search: "https://apps.dos.ny.gov/publicInquiry/", notes: "NY LLCs must also publish a notice in two newspapers (filing fees apply).", fees: { LLC: { cents: 20000, time: "~2-3 weeks" }, FOR_PROFIT: { cents: 12500, time: "~2-3 weeks" }, NON_PROFIT: { cents: 7500, time: "~2-3 weeks" } } },
  { code: "NC", name: "North Carolina", sos: "https://www.sosnc.gov/", search: "https://www.sosnc.gov/online_services/search/Business_Registration_Search", fees: { LLC: { cents: 12500, time: "~7-10 business days" }, FOR_PROFIT: { cents: 12500, time: "~7-10 business days" }, NON_PROFIT: { cents: 6000, time: "~7-10 business days" } } },
  { code: "ND", name: "North Dakota", sos: "https://www.nd.gov/sos/", search: "https://firststop.sos.nd.gov/search/business", fees: { LLC: { cents: 13500, time: "~3-5 business days" }, FOR_PROFIT: { cents: 13500, time: "~3-5 business days" }, NON_PROFIT: { cents: 13500, time: "~3-5 business days" } } },
  { code: "OH", name: "Ohio", sos: "https://www.ohiosos.gov/", search: "https://businesssearch.ohiosos.gov/", fees: { LLC: { cents: 9900, time: "~2-4 business days" }, FOR_PROFIT: { cents: 9900, time: "~2-4 business days" }, NON_PROFIT: { cents: 9900, time: "~2-4 business days" } } },
  { code: "OK", name: "Oklahoma", sos: "https://www.sos.ok.gov/", search: "https://www.sos.ok.gov/business/corp/search.aspx", fees: { LLC: { cents: 10000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 5000, time: "~3-5 business days" }, NON_PROFIT: { cents: 2500, time: "~3-5 business days" } } },
  { code: "OR", name: "Oregon", sos: "https://sos.oregon.gov/", search: "https://sos.oregon.gov/business/Pages/find-a-business.aspx", fees: { LLC: { cents: 10000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 10000, time: "~5-7 business days" }, NON_PROFIT: { cents: 5000, time: "~5-7 business days" } } },
  { code: "PA", name: "Pennsylvania", sos: "https://www.pa.gov/agencies/paos.html", search: "https://www.corporations.pa.gov/Search/corpsearch", fees: { LLC: { cents: 12500, time: "~2-3 weeks (expedited available)" }, FOR_PROFIT: { cents: 12500, time: "~2-3 weeks (expedited available)" }, NON_PROFIT: { cents: 7000, time: "~2-3 weeks" } } },
  { code: "RI", name: "Rhode Island", sos: "https://www.sos.ri.gov/", search: "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx", fees: { LLC: { cents: 15000, time: "~2-3 weeks" }, FOR_PROFIT: { cents: 15000, time: "~2-3 weeks" }, NON_PROFIT: { cents: 15000, time: "~2-3 weeks" } } },
  { code: "SC", name: "South Carolina", sos: "https://www.scsos.com/", search: "https://businessfilings.sc.gov/BusinessFiling/Entity/Search", fees: { LLC: { cents: 11000, time: "~7-10 business days" }, FOR_PROFIT: { cents: 13500, time: "~7-10 business days" }, NON_PROFIT: { cents: 13500, time: "~7-10 business days" } } },
  { code: "SD", name: "South Dakota", sos: "https://sdsos.gov/", search: "https://sosenterprise.sd.gov/BusinessServices/Search/Business.aspx", fees: { LLC: { cents: 15000, time: "~3-5 business days" }, FOR_PROFIT: { cents: 15000, time: "~3-5 business days" }, NON_PROFIT: { cents: 15000, time: "~3-5 business days" } } },
  { code: "TN", name: "Tennessee", sos: "https://sos.tn.gov/", search: "https://sos.tn.gov/business-services/search-business", fees: { LLC: { cents: 30000, time: "~7-10 business days" }, FOR_PROFIT: { cents: 30000, time: "~7-10 business days" }, NON_PROFIT: { cents: 30000, time: "~7-10 business days" } } },
  { code: "TX", name: "Texas", sos: "https://www.sos.state.tx.us/", search: "https://mycpa.cpa.state.tx.us/coa/", notes: "Texas imposes a $750/yr franchise tax (waived for many small LLCs).", fees: { LLC: { cents: 30000, time: "~5-7 business days (expedited available)" }, FOR_PROFIT: { cents: 30000, time: "~5-7 business days" }, NON_PROFIT: { cents: 30000, time: "~5-7 business days" } } },
  { code: "UT", name: "Utah", sos: "https://corporations.utah.gov/", search: "https://secure.utah.gov/bes/", fees: { LLC: { cents: 7000, time: "~1-2 business days (online)" }, FOR_PROFIT: { cents: 7000, time: "~1-2 business days (online)" }, NON_PROFIT: { cents: 7000, time: "~1-2 business days (online)" } } },
  { code: "VT", name: "Vermont", sos: "https://sos.vermont.gov/", search: "https://bizfilings.vermont.gov/online/BusinessInquire", fees: { LLC: { cents: 12500, time: "~3-5 business days" }, FOR_PROFIT: { cents: 12500, time: "~3-5 business days" }, NON_PROFIT: { cents: 12500, time: "~3-5 business days" } } },
  { code: "VA", name: "Virginia", sos: "https://www.scc.virginia.gov/", search: "https://cis.scc.virginia.gov/EntitySearch/Index", fees: { LLC: { cents: 10000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 10000, time: "~5-7 business days" }, NON_PROFIT: { cents: 10000, time: "~5-7 business days" } } },
  { code: "WA", name: "Washington", sos: "https://www.sos.wa.gov/", search: "https://ccfs.sos.wa.gov/", notes: "Washington imposes a Business & Occupation tax on revenue.", fees: { LLC: { cents: 20000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 20000, time: "~5-7 business days" }, NON_PROFIT: { cents: 3000, time: "~5-7 business days" } } },
  { code: "WV", name: "West Virginia", sos: "https://sos.wv.gov/", search: "https://business4.wv.gov/businesssearch/", fees: { LLC: { cents: 10000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 10000, time: "~5-7 business days" }, NON_PROFIT: { cents: 10000, time: "~5-7 business days" } } },
  { code: "WI", name: "Wisconsin", sos: "https://www.wdfi.org/", search: "https://www.wdfi.org/apps/CorpSearch/", fees: { LLC: { cents: 13000, time: "~5-7 business days" }, FOR_PROFIT: { cents: 10000, time: "~5-7 business days" }, NON_PROFIT: { cents: 10000, time: "~5-7 business days" } } },
  { code: "WY", name: "Wyoming", sos: "https://sos.wyo.gov/", search: "https://wyobiz.wy.gov/Business/FilingSearch.aspx", notes: "Wyoming is a popular low-cost, business-friendly formation state.", fees: { LLC: { cents: 10000, time: "~1-2 business days" }, FOR_PROFIT: { cents: 10000, time: "~1-2 business days" }, NON_PROFIT: { cents: 10000, time: "~1-2 business days" } } },
];
